FROM python:3.10.6

WORKDIR /app

RUN apt update && \
    apt install -y curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-$(arch).zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    echo 'complete -C /usr/local/bin/aws_completer aws' >> /etc/bash.bashrc
